accounts/urls.py
"""accounts URL Configuration

"""
from django.conf.urls import url
from django.contrib.auth.views import logout
from accounts import views

urlpatterns = [ 
    url(r"^send_login_email$", views.send_login_email, name="send_login_email"),
    url(r"^login$", views.login, name="login"), 
    url(r"^logout$", logout, {"next_page": "/"}, name="logout"),
]

games/urls.py
from django.conf.urls import url
from games import views

urlpatterns = [
    url(r"^new$", views.new_player, name="new_player"),
    url(r"^(\d+)/$", views.view_player, name="view_player"),        
    #url(r"^(\d+)/add_game$", views.add_game, name="add_game"),
    # url(r'^admin/', admin.site.urls),
]

squashing/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from games import views as game_views
from games import urls as players_urls
from accounts import urls as accounts_urls


urlpatterns = [
	url(r'^$', game_views.home_page, name="home"),
	url(r"^players/", include(players_urls)),
	url(r"^players/", include(players_urls)),
	url(r"^accounts/", include(accounts_urls)), 
	# url(r"^players/new$", views.new_player, name="new_player"),
	# url(r"^players/(\d+)/$", views.view_player, name="view_player"),
	# url(r"^players/(\d+)/add_game$", views.add_game, name="add_game"),
	# url(r'^admin/', admin.site.urls),
]

accounts/models.py
import uuid
from django.contrib import auth
from django.db import models

auth.signals.user_logged_in.disconnect(auth.models.update_last_login)

class User(models.Model):
  email = models.EmailField(primary_key=True)  
  REQUIRED_FIELDS = []
  USERNAME_FIELD = "email"
  is_anonymous = False
  is_authenticated = True


class Token(models.Model):
  email = models.EmailField()
  uid = models.CharField(default=uuid.uuid4, max_length=40)

games/models.py
from django.db import models
from django.core.urlresolvers import reverse

# Create your models here.
class Player(models.Model):
  name    = models.TextField(default="")
  objects = models.Manager()
  
  def get_absolute_url(self):
    response = reverse("view_player", args=[self.id])  # pylint: disable=no-member 
    return response
  
class Game(models.Model):
  objects = models.Manager()
  player  = models.ForeignKey(Player, default=None)
  text    = models.TextField(default="")

  class Meta:
    ordering = ('id', )
    unique_together = ('player', 'text')
  # player1 = models.TextField(default="Player1")
  # player2 = models.TextField(default="Player2")
  # score1  = models.IntegerField(default=0)
  # score2  = models.IntegerField(default=0)
  
  def __str__(self):
    return self.text

games/forms.py
from django import forms
from django.core.exceptions import ValidationError
from games.models import Game

EMPTY_GAME_ERROR = "You can't have an empty game."
DUPLICATE_GAME_ERROR  = "You've saved this game already."


class GameForm(forms.models.ModelForm):
  
  class Meta:
    model   = Game
    fields  = (
      "text",
    )
    widgets = {
      'text': forms.fields.TextInput(attrs={
          'placeholder': "Enter game <SCORE : PLAYER_AGAINST>",
          'class': 'form-control input-lg', 
    }) }
    error_messages = { 
        'text': {'required': EMPTY_GAME_ERROR}
    }

  def save(self, for_player):
    self.instance.player = for_player
    return super().save()


class ExistingGameForm(GameForm):
  def __init__(self, for_player, *args, **kwargs):
      super().__init__(*args, **kwargs)
      self.instance.player = for_player
  
  def validate_unique(self):
    try:
        self.instance.validate_unique()
    except ValidationError as err:
        err.error_dict = {'text': [DUPLICATE_GAME_ERROR]}
        self._update_errors(err)

  def save(self):
    the_save = forms.models.ModelForm.save(self)
    return the_save

accounts/views.py
from django.contrib import auth, messages
from django.core.mail import send_mail
from django.core.urlresolvers import reverse 
from django.shortcuts import redirect, render
from accounts.models import Token


def send_login_email(request):
  an_email = request.POST["email"]
  token = Token.objects.create(email=an_email)
  url = request.build_absolute_uri("{}?token={}".\
      format(reverse("login"), str(token.uid)))
  message_body = f"Use this link to log in:\n\n{ url }"
  send_mail(
      "Login link for Squashitlan", 
      message_body, 
      "diego.villamil@squashitlan.com", 
      [an_email])
  messages.success(request, 
      "Check your email, we've sent you a link to log in.")
  response = redirect("/")
  return response

def login(request):
  token_id = request.GET.get("token")
  user = auth.authenticate(uid=token_id)
  if user is not None:
    auth.login(request, user)
  response = redirect("/")
  return response

  

games/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.core.exceptions import ValidationError

from games.forms import GameForm, ExistingGameForm, EMPTY_GAME_ERROR
from games.models import Game, Player

# Create your views here.

def home_page(request):
  a_form = GameForm()
  response = render(request, "home.html", {"form": a_form})
  return response

def new_player(request):
  a_form = GameForm(data=request.POST)
  if a_form.is_valid():
    player = Player.objects.create()
    a_form.save(for_player = player)
    response = redirect(player)
  else:
    response = render(request, "home.html", {"form": a_form})
  return response
  

def view_player(request, player_id):
  player = Player.objects.get(id=player_id)
  if request.method != "POST":
    a_form   = ExistingGameForm(for_player=player)
    response = render(request, 'player.html', {
        'player': player, "form": a_form})
  else:
    a_form = ExistingGameForm(for_player=player, data=request.POST)
    if a_form.is_valid():
      a_form.save()
      response = redirect(player)
    else:
      response = render(request, 'player.html', {
          'player': player, "form": a_form})
  return response
 

games/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Games played</title>
  <link href="/static/bootstrap/css/bootstrap.min.css" rel="stylesheet">
  <link href="/static/base.css" rel="stylesheet">
</head>

<body>
  <div class="container">
    <nav class="navbar navbar-default" role="navigation">
      <div class="container-fluid">
        <a class="navbar-brand" href="/">Squashitlan</a>
        {% if user.email %}
          <ul class="nav navbar-nav navbar-right">
            <li class="navbar-text">Logged in as {{ user.email }}</li>
            <li><a href="{% url 'logout' %}">Log out</a></li>
          </ul>
        {% else %}
          <form class="navbar-form navbar-right" 
                method="POST" 
                action="{% url 'send_login_email' %}">
            <span>Enter email to log in:</span>
            <input class="form-control" name="email" type="text"/>
            {% csrf_token %}
          </form>
        {% endif %}
      </div>
    </nav> 

    {% if messages %}
      <div class="row">
        <div class="col-md-8">
          {% for message in messages %}
            {% if message.level_tag == 'success' %}
              <div class="alert alert-success">{{ message }}</div>
            {% else %}
              <div class="alert alert-warning">{{ message }}</div>
            {% endif %}
          {% endfor %}
        </div>
      </div>
    {% endif %}

    <div class="row">
      <div class="col-md-6 col-md-offset-3 jumbotron">
        <div class="text-center">

          <h1>{% block header_text %}{% endblock %}</h1>
          <form method="POST" action="{% block form_action %}{% endblock%}">
            {{ form.text }} 
            {% csrf_token %}
            {% if form.errors %}
              <div class="form-group has-error">
                <span class="help-block">{{ form.text.errors }}</span>
              </div>
            {% endif %}
          </form>
          {% block table %}
          {% endblock %}
        
        </div>
      </div>
    </div>
  </div>


  <script src="/static/jquery-3.3.1.min.js"></script>
  <script src="/static/player.js"></script>
  <script>
    $(document).ready(function () {
      window.Squashing.initialize()
    })
  </script>

</body>

</html>

games/templates/home.html
{% extends "base.html" %}

{% block header_text %}
  New player
{% endblock %}

{% block form_action %}
  {% url "new_player" %}
{% endblock %}

games/templates/player.html
{% extends "base.html" %}

{% block header_text %}
  Games played
{% endblock %}

{% block form_action %}
  {% url "view_player" player.id %}
{% endblock%}

{% block table %}
  <table id="id_game_table" class="table">
    {% for a_game in player.game_set.all %}
      <tr><td>{{ forloop.counter }}: {{ a_game.text }}</td></tr>
    {% endfor %}
  </table>
{% endblock %}